### PR TITLE
Update Policies.json

### PR DESCRIPTION
**Pull request by EmperorPinguin**
This will reduce the amount of reloads required by at least 90%.

### CODE REVIEW

**Comment by Belias02** [comment]
It would but that would make that policy too OP and it is not intended to be used that way. If someone is going to take advantage of the reload function, then they should pass through that.

**Comment by EmperorPinguin** [comment]
The outcome of a turn is the same, and thus wouldn't make the policy more OP than it already is (it is very OP). "25% chance" doesn't exist in Unciv mp; you can just reload until you get what you want. For Germany in the base game it isn't too bad, but Deciv is unplayable because of it. It's up to you.

**Comment by EmperorPinguin** [comment]
I think it's better if the unit-capture part is removed entirely; it's OP, and it's unrealistic for soldiers to switch sides every turn.

**Comment by Belias02** [comment]
I made an oversight, it was meant to only capture barbarians. By the way, what do you think about making it a 10% chance? So people would not try to abuse of the reload. And lower the water gain to 10.

**Comment by Belias02** [comment]
And only with barbarians, which have the raider promotion and get less XP

**Pull request closed without merging**
